spring:
  application:
    name: springboot-lab
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_lab?useTimezone=true&serverTimezone=UTC
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:arthurbr123}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      format_sql: true
    show-sql: false
    open-in-view: false
logging:
  level:
    root: WARN
   # com.thurdass.springboot_lab: DEBUG
